const monsters = [
  {
    name: "Slime",
    power: "1",
    img: "https://dragon-quest.org/images/thumb/d/dd/DQVIII_Slime.png/375px-DQVIII_Slime.png",
    types: ["Slime"],
    id: 1,
    created_at: new Date(),
  },
  {
    name: "She-slime",
    power: "5",
    img: "https://dragon-quest.org/images/thumb/5/5d/DQVIII_She-Slime.png/360px-DQVIII_She-Slime.png",
    types: ["Slime"],
    id: 2,
    created_at: new Date(),
  },
  {
    name: "Metal slime",
    power: "50",
    img: "https://dragon-quest.org/images/thumb/1/1b/DQVIII_Metal_Slime.png/375px-DQVIII_Metal_Slime.png",
    types: ["Slime", "Metal"],
    id: 3,
    created_at: new Date(),
  },
  {
    name: "Metal king slime",
    power: "500",
    img: "https://dragon-quest.org/images/thumb/3/3a/DQVIII_Metal_King_Slime.png/413px-DQVIII_Metal_King_Slime.png",
    types: ["Slime", "Metal"],
    id: 4,
    created_at: new Date(),
  },
  {
    name: "Medislime",
    power: "60",
    img: "https://dragon-quest.org/images/b/b4/DQIV_Medislime.png",
    types: ["Slime", "Fairy"],
    id: 5,
    created_at: new Date(),
  },
  {
    name: "Liquid metal slime",
    power: "120",
    img: "https://dragon-quest.org/images/thumb/c/c0/DQVIII_Liquid_Metal_Slime.png/450px-DQVIII_Liquid_Metal_Slime.png",
    types: ["Slime", "Metal"],
    id: 6,
    created_at: new Date(),
  },
  {
    name: "King cureslime",
    power: "150",
    img: "https://dragon-quest.org/images/thumb/2/2f/DQVIII_King_Cureslime.png/375px-DQVIII_King_Cureslime.png",
    types: ["Slime", "Fairy"],
    id: 7,
    created_at: new Date(),
  },
  {
    name: "Cureslime",
    power: "45",
    img: "https://dragon-quest.org/images/thumb/f/ff/DQVIII_Cureslime.png/300px-DQVIII_Cureslime.png",
    types: ["Slime", "Fairy"],
    id: 8,
    created_at: new Date(),
  },
  {
    name: "King slime",
    power: "140",
    img: "https://dragon-quest.org/images/thumb/6/6c/DQVIII_King_Slime.png/375px-DQVIII_King_Slime.png",
    types: ["Slime"],
    id: 9,
    created_at: new Date(),
  },
  {
    name: "Healslime",
    power: "15",
    img: "https://dragon-quest.org/images/thumb/6/66/DQVIII_Healslime.png/300px-DQVIII_Healslime.png",
    types: ["Slime", "Fairy"],
    id: 10,
    created_at: new Date(),
  },
  {
    name: "Bubble slime",
    power: "20",
    img: "https://dragon-quest.org/images/thumb/9/9a/DQVIII_Bubble_Slime.png/375px-DQVIII_Bubble_Slime.png",
    types: ["Slime", "Toxic"],
    id: 11,
    created_at: new Date(),
  },
];

module.exports = monsters;
